name: Go

on: [push, pull_request]

jobs:

  test:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.12.17', '1.13.15', '1.14.7', '1.15']
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go }}
    steps:
      - if: startsWith(matrix.os, 'macos')
        run: brew update

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Get Build Tools
        run: |
          go get github.com/ory/go-acc

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - uses: actions/checkout@v2

      - name: Test
        run: go-acc .

      - name: Build
        run: go build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,GO
          file: coverage.txt

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml